name: C/C++ CI

on:
  push:
    branches: [ daisy, feature/* ]
  pull_request:
    branches: [ daisy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Setup arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10.3-2021.10' # The arm-none-eabi-gcc release to use.
    - name: make
      run: make
